services:
  make:
    image: klipper:${TAG:-latest}-mcu
    build:
        context: docker/klipper
        target: mcu
    tty: true
    privileged: true
    entrypoint: make
    working_dir: /opt/klipper
    volumes:
      - /dev:/dev
      - ./config/build.config:/opt/klipper/.config
      - ./out:/opt/klipper/out
