## Service Definitions
services:

  ## Klippy Services
  ##
  klipper:
    image: mkuf/klipper:latest
    restart: unless-stopped
    privileged: true
    logging:
      driver: none
    command: >
      -I printer_data/run/klipper.tty
      -a printer_data/run/klipper.sock
      printer_data/config/printer.cfg
      -l printer_data/logs/klippy.log
    volumes:
      - /dev:/dev
      - ./config:/opt/printer_data/config
      - run:/opt/printer_data/run
      - gcode:/opt/printer_data/gcodes
      - log:/opt/printer_data/logs
    # labels:
    #  - org.prind.service=klipper

  ## WebApi
  ##
  moonraker:
    image: mkuf/moonraker:latest
    restart: unless-stopped
    pid: host
    logging:
      driver: none
      klipper:
        condition: service_started
    volumes:
      - /dev/null:/opt/klipper/config/null
      - /dev/null:/opt/klipper/docs/null
      - /run/dbus:/run/dbus
      - /run/systemd:/run/systemd
      - run:/opt/printer_data/run
      - gcode:/opt/printer_data/gcodes
      - log:/opt/printer_data/logs
      - moonraker-db:/opt/printer_data/database
      - ./config:/opt/printer_data/config
    # labels:
      # - org.prind.service=moonraker
      # - traefik.enable=true
      # - traefik.http.services.moonraker.loadbalancer.server.port=7125
      # have to manage traefik myself because of
      # - https://github.com/coollabsio/coolify/issues/5235
      # - https://github.com/coollabsio/coolify/issues/5555
      #- traefik.http.routers.moonraker.rule: PathRegexp(`^/(websocket|printer|api|access|machine|server)`)
      #- traefik.http.routers.moonraker.entrypoints: web
      # - traefik.http.routers.moonraker.rule=Host(`moonraker`) && PathPrefix(`/`)
      # - traefik.http.routers.moonraker.entrypoints=http

  ## Frontends
  ##

  mainsail:
    image: ghcr.io/mainsail-crew/mainsail:edge
    restart: unless-stopped
    # labels:
      # - org.prind.service=mainsail
      # - traefik.enable=true
      # - traefik.http.services.mainsail.loadbalancer.server.port: 80
      # - traefik.http.routers.mainsail.rule: PathPrefix(`/`)
      # - traefik.http.routers.mainsail.entrypoints: web
      # - traefik.http.routers.mainsail.rule=Host(`3d.ok.lan`) && PathPrefix(`/`)
      # - traefik.http.routers.mainsail.entrypoints=http


volumes:
  run:
    driver_opts:
      type: tmpfs
      device: tmpfs
  gcode:
  moonraker-db:
  log:
    driver_opts:
      type: tmpfs
      device: tmpfs
  
